import { LineEdit, AboutSlint, Button, VerticalBox } from "std-widgets.slint";

export struct Definition {
    word:string,
    definition: string,
    examples:string
}

export component MainWindow {
    in property <[Definition]> definitions;
    callback search(string);
    VerticalBox {
        Text {
            text: "Merry Dictionary";
            font-size: 24px;
            horizontal-alignment: center;
        }
        HorizontalLayout { 
            alignment: center;
            spacing: 5px;
            search-box := LineEdit {
                font-size: 14px;
                placeholder-text: "Enter a word...";
                accepted(text) => {
                    root.search(self.text);
                    self.text = "";
                }
            }
            btn := Button {
                text: "Search";
                clicked => {
                    root.search(search-box.text);
                    search-box.text = "";
                }
                enabled: search-box.text != "";
            }
        }
        VerticalLayout {
            for data in root.definitions: definitions := VerticalLayout { 
                Text {
                    text: data.definition;
                    font-size: 15px;
                    horizontal-alignment: left;
                    wrap: word-wrap;
                }
            }
        }
        Rectangle {}
        AboutSlint {
            preferred-height: 50px;
        }
    }
}
/*

    in-out property <[{definition:string, example:string,word:string}]> definitions:[
        {
            word:"yash",
            definition:"def of yash",
            example:"example of yash",
        },
        {
            word:"josh",
            definition:"def of josh",
            example:"example of josh",
        }
    ];
            for data in root.definitions: definitions := VerticalLayout { 
                Text {
                    text: data.word;
                    font-size: 15px;
                    horizontal-alignment: left;
                    wrap: word-wrap;
                }
                Text {
                    text: data.definition;
                    font-size: 15px;
                    horizontal-alignment: left;
                    wrap: word-wrap;
                }
                Text {
                    text: data.example;
                    font-size: 15px;
                    horizontal-alignment: left;
                    wrap: word-wrap;
                }
            }
*/
